services:
  telegram-bot:
    build:
      dockerfile: images/telegram-bot/Dockerfile
    container_name: telegram-bot-container

  recommendation-system:
    build:
      dockerfile: images/recommendation-system/Dockerfile
    container_name: recommendation-system-container
