name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies in telegram-bot
        run: |
          python -m pip install --upgrade pip
          pip install -r code/telegram-bot/requirements.txt
      - name: Install dependencies in test
        run: |
          python -m pip install --upgrade pip
          pip install -r code/test/requirements.txt
      - name: Install dependencies in recomendation-system
        run: |
          python -m pip install --upgrade pip
          pip install -r code/recomendation-system/requirements.txt