name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies in telegram-bot
        run: |
          python -m pip install --upgrade pip
          pip install -r telegram-bot/dependencies/requirements.txt
      - name: Install dependencies in recommendation-system
        run: |
          python -m pip install --upgrade pip
          pip install -r recommendation-system/dependencies/requirements.txt